services:
  db:
    image: postgres:14.5-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: web
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8001
    depends_on:
      - db
volumes:
  postgres_data:
