services:
  
  web:
    build: .
    container_name: web
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8001
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres_data:
