services:
  db:
    image: postgres:14.5-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    

  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_data:/app/staticfiles
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80" # Exposição pública
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Configuração do Nginx
      - static_data:/usr/share/nginx/html/staticfiles # Ponto crítico: Leitura do volume estático
    depends_on:
      - web

volumes:
  postgres_data:
  static_data:


