# Generated by Django 4.2.14 on 2024-08-05 20:08

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(db_index=True, max_length=11, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('VIGILANCIA', 'Vigilância'), ('UNIVERSIDADE', 'Universidade'), ('ADMINISTRACAO', 'Administração'), ('PREFEITURA', 'Prefeitura'), ('EMPRESA', 'Empresa'), ('OUTRO', 'Outro')], max_length=13)),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['-tipo_usuario', 'nome'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
