# Generated by Django 4.2.16 on 2024-12-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_user_options_alter_user_tipo_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-tipo_usuario', 'nome'], 'permissions': [('pode_cadastrar', 'pode cadastrar outros usuarios')], 'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
    ]
