# Generated by Django 4.2.16 on 2025-01-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0009_alter_formulario_questao1_alter_formulario_questao10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='classificacao',
            field=models.TextField(default='Não possui classificação'),
        ),
    ]
