# Generated by Django 4.2.16 on 2024-12-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_user_tipo_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-tipo_usuario', 'nome'], 'permissions': [('view_user_vigilancia', 'Pode visualizar usuários de Vigilância'), ('view_user_outro', 'Pode visualizar usuários Comuns'), ('view_user_prefeitura', 'Pode visualizar usuários Prefeitura'), ('view_user_adm', 'Pode visualizar usuários Administradores'), ('view_create_user_outro', 'Pode Criar usuários do tipo outro'), ('view_create_user_vigilancia', 'Pode Criar usuários do tipo vigilancia'), ('view_create_user_prefeitura', 'Pode Criar usuários do tipo prefeitura'), ('avaliar_restaurantes', 'Pode Salvar A avaliação dos restaurantes no banco de dados')], 'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('VIGILANCIA', 'Vigilância'), ('PREFEITURA', 'Prefeitura'), ('ADM', 'Administrador'), ('OUTRO', 'Outro')], max_length=13),
        ),
    ]
