# Generated by Django 4.2.16 on 2024-11-22 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_alter_empresa_classificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='tem_alvara',
        ),
        migrations.AddField(
            model_name='empresa',
            name='redes_sociais',
            field=models.CharField(blank=True, max_length=100, verbose_name='Possui Redes sociais? '),
        ),
        migrations.AddField(
            model_name='empresa',
            name='site',
            field=models.CharField(blank=True, max_length=100, verbose_name='link do site se possuir'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='alvara',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'Alvará deve conter apenas letras e números')], verbose_name='Alvara/licença sanitaria '),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, verbose_name='CNPJ '),
        ),
    ]
