# Generated by Django 4.2.16 on 2024-10-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100, verbose_name='razão social: ')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='Nome Fantasia: ')),
                ('alvara', models.CharField(max_length=50, verbose_name='Alvara/licença sanitaria ')),
                ('inscricao', models.CharField(max_length=20, verbose_name='Inscrição Estadual / Municipal ')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ/CPF ')),
                ('fone', models.CharField(max_length=20, verbose_name='Fone: ')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='E-MAIL: ')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço(Rua/Av): ')),
                ('complemento', models.CharField(max_length=50, verbose_name='Complemento: ')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro: ')),
                ('municipio', models.CharField(max_length=50, verbose_name='Município: ')),
                ('uf', models.CharField(max_length=2, verbose_name='-UF: ')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP: ')),
                ('cnae', models.CharField(choices=[('refeições', '5611-2/01 - restaurantes e similares'), ('bebidas', '5611-2/02 - bares e outros estabelecimentos especializados  em   servir bebidas'), ('lanches', '5611-2/03- lanchonetes, casas de chá, de sucos e similares')], default='', max_length=10, verbose_name='Classificação Nacional da Atividade Econômica (CNAE)')),
                ('numero_de_refeicoes', models.CharField(choices=[('100', 'até 100'), ('101 A 300', '101 a 300'), ('301 A 1000', '301 a 1000'), ('1001 A 2500', '1001 a 2500'), ('mais de 2500', 'acima de 2500')], default='', max_length=12, verbose_name='Número de refeições servidas diariamente')),
                ('numero_funcionarios', models.CharField(choices=[('1 A 4', 'de 1 a 4'), ('5 A 9', '5 a 9'), ('10 A 19', '10 a 19'), ('mais de 20', '20 ou mais')], default='', max_length=10, verbose_name='Pessoal ocupado (número de pessoas envolvidas nesta atividade econômica/ n° funcionários):')),
                ('tem_responsavel', models.CharField(choices=[('SIM', 'sim'), ('NAO', 'não')], default='', max_length=10, verbose_name='Tem responsável pelas Boas Práticas?')),
                ('formacao_academica', models.CharField(choices=[('CA', 'Curso de Capacitação'), ('NT', 'Nível Técnico'), ('NS', 'Nível Superior')], default='', max_length=10, verbose_name='Formação Acadêmica')),
                ('responsavel_legal', models.CharField(max_length=100, verbose_name='Responsável Legal/ Responsável legal do Estabelecimento:')),
                ('tem_alvara', models.CharField(choices=[('SIM', 'sim'), ('NÃO', 'NÃO'), ('EP', 'em processo'), ('NA', 'não se aplica')], default='', max_length=10, verbose_name='Possui Alvará Sanitário*?')),
            ],
        ),
        migrations.DeleteModel(
            name='Formulario',
        ),
    ]
