# Generated by Django 4.2.16 on 2024-11-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_empresa_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='classificacao',
            field=models.CharField(default='PENDENTE', max_length=100),
        ),
    ]
