# Generated by Django 4.2.16 on 2024-11-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_remove_empresa_tem_alvara_empresa_redes_sociais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='alvara',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='classificacao',
            field=models.CharField(default='Não Possui Avaliação', max_length=100),
        ),
    ]
