# Generated by Django 4.2.16 on 2025-03-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_remove_empresa_alvara_alter_empresa_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnae',
            field=models.CharField(choices=[('5611-2/01', '5611-2/01 - restaurantes e similares'), ('5611-2/02', '5611-2/02 - bares e outros estabelecimentos especializados  em   servir bebidas'), ('5611-2/03', '5611-2/03- lanchonetes, casas de chá, de sucos e similares'), ('OUTRO', 'OUTRO')], default='', max_length=10, verbose_name='Classificação Nacional da Atividade Econômica (CNAE)'),
        ),
    ]
