name: Deploy - Categoriza

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Deploy para Dokploy
        env:
          DOKPLOY_API_KEY: ${{ secrets.DOKPLOY_API_KEY }}
          DOKPLOY_APP_ID: ${{ secrets.DOKPLOY_APP_ID }}
          DOKPLOY_URL: ${{ secrets.DOKPLOY_URL }}
        run: |
          curl -X POST "${{ env.DOKPLOY_URL }}/api/v1/applications/${{ env.DOKPLOY_APP_ID }}/deploy" \
            -H "Authorization: Bearer ${{ env.DOKPLOY_API_KEY }}" \
            -H "Content-Type: application/json"
